version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
      # Only get updates for garminconnect
      allow:
          - dependency-name: "garminconnect"
      # Should open PRs against the dev branch, not main
      target-branch: "dev"
