version: "3.8"

services:
  app:
    restart: "no"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # Mount .env file at startup (left path should be local path of your config file)
    volumes:
      - ${ENV_PATH:-../../.env}:/app/.env:ro # Will use ENV_PATH if non-empty
      - "../../session:/session"
    environment:
      - PYTHONUNBUFFERED=1
