version: "3.8"

name: garmin

# Docker compose config for development. First ensure host paths are correct, then run:
# docker-compose up --build

services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile

        command: ["--allow-root"]
        env_file:
            - ../../dev.env
        volumes:
            - ../../data:/app/data

        environment:
            - PYTHONUNBUFFERED=1 # Prevents Python from buffering stdout and stder
            # Overwrite the session path in the .env file, if this is different when running in docker (should be the same path as the data volume under "volumes" above)
            - SESSION_FILE_PATH=/app/data
            - POETRY_VIRTUALENVS_CREATE=false
