name: update-requirements
on:
    push:
        branches:
            - "*"
        paths:
            - "poetry.lock"
            - "pyproject.toml"
    pull_request:
        branches:
            - "*"
        paths:
            - "poetry.lock"
            - "pyproject.toml"

env:
    HAS_DEPS_CHANGED: false

jobs:
    # Update requirements.txt file (for non-poetry users) if the poetry dependencies change
    update-requirements:
        runs-on: ubuntu-latest
        permissions: # To be able to commit the updated requirements.txt file
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - run: |
                  pip install poetry

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
                  cache: "poetry"

            - name: Generate requirements.txt
              run: poetry export -f requirements.txt --output requirements.txt --without-hashes

              # Check if the export changed anything in requirements.txt
            - name: Check for changes
              run: |
                  git add requirements.txt
                  if git diff --staged --exit-code -- requirements.txt; then
                      echo "No changes to requirements.txt"
                  else
                      echo "HAS_DEPS_CHANGED=true" >> $GITHUB_ENV
                  fi
              continue-on-error: true

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              if: env.HAS_DEPS_CHANGED
              with:
                  message: "[Automated] Update requirements.txt"
                  add: "requirements.txt"
                  default_author: github_actions
